const Detail = [ 
  
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    {
        id: 1,
        Title: "2 Kva 12 Hours Availability", 
        Price: "50k monthly price",
        Img: "./Images/sol7.png",
        Name: "Specifications",
        Logo: "Images/sol logos.png",
        Amount: "₦5,666.00 • Lease to own plan",
        Note: "it can power bla bla bla just checking if it will upload thank you",
    },
    
    ]

export default Detail